name: Simple Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mindit-ai:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mindit-ai:latest

      # Removed SCP step; deployment will pull from Docker Hub

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DOCKERHUB_USERNAME,DOCKERHUB_TOKEN,GITHUB_SHA
          script: |
            #기존 컨테이너 중지 및 제거
            sudo docker stop mindit-ai-container 2>/dev/null || true
            sudo docker rm mindit-ai-container 2>/dev/null || true

            #이미지 정리 (공간 확보)
            sudo docker image prune -af 2>/dev/null || true

            #Docker Hub 로그인 및 최신 이미지 가져오기
            echo "$DOCKERHUB_TOKEN" | sudo docker login -u "$DOCKERHUB_USERNAME" --password-stdin || exit 1
            sudo docker pull "$DOCKERHUB_USERNAME/mindit-ai:${GITHUB_SHA}" || exit 1
            sudo docker tag "$DOCKERHUB_USERNAME/mindit-ai:${GITHUB_SHA}" "$DOCKERHUB_USERNAME/mindit-ai:latest"
            sudo docker tag "$DOCKERHUB_USERNAME/mindit-ai:${GITHUB_SHA}" mindit-ai:latest

            #새 컨테이너 실행
            sudo docker run -d \
              --name mindit-ai-container \
              --restart unless-stopped \
              -p 8000:8000 \
              -e PYTHONPATH=/app \
              -e PYTHONUNBUFFERED=1 \
              mindit-ai:latest

            #헬스체크
            sleep 10
            # 컨테이너 상태 확인
            sudo docker ps | grep mindit-ai-container || exit 1
