name: Simple Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t mindit-ai:${{ github.sha }} .
          docker save mindit-ai:${{ github.sha }} | gzip > mindit-ai-image.tar.gz

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "mindit-ai-image.tar.gz"
          target: "/home/ubuntu/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            #기존 컨테이너 중지 및 제거
            sudo docker stop mindit-ai-container 2>/dev/null || true
            sudo docker rm mindit-ai-container 2>/dev/null || true

            #기존 이미지 제거
            sudo docker rmi mindit-ai:latest 2>/dev/null || true

            #새 이미지 로드
            sudo docker load < /home/ubuntu/mindit-ai-image.tar.gz
            sudo docker tag mindit-ai:${{ github.sha }} mindit-ai:latest

            #새 컨테이너 실행
            sudo docker run -d \
              --name mindit-ai-container \
              --restart unless-stopped \
              -p 8000:8000 \
              -e PYTHONPATH=/app \
              -e PYTHONUNBUFFERED=1 \
              mindit-ai:latest

            #임시 파일 정리
            sudo rm -f /home/ubuntu/mindit-ai-image.tar.gz

            #헬스체크
            sleep 10
            # 컨테이너 상태 확인
            sudo docker ps | grep mindit-ai-container || exit 1
